version: '3'
services:
  mysql:
    image: my-mysql-image
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

  redis:
    image: my-redis-image
    ports:
      - "6379:6379"