# Production Environment
# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/your_postgres_db
spring.datasource.username=your_postgres_user
spring.datasource.password=your_postgres_password

# Redis Configuration
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=your_redis_password # Optional

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/your_mongo_db