spring.application.name=user-management-service
# Default profile
spring.profiles.active=dev

#temp to skip this config when no need getting real data....
#spring.datasource.url=jdbc:mysql://localhost:3306/my_database
#spring.datasource.username=my_username
#spring.datasource.password=my_password
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#default port for H2 console when connecting to H2 DB is 8082

# H2 Database Configuration
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# PostgreSQL Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/your_postgres_db
#spring.datasource.username=your_postgres_user
#spring.datasource.password=your_postgres_password

# MongoDB Configuration
#spring.data.mongodb.uri=mongodb://localhost:27017/your_mongo_db

# Redis Configuration
#spring.redis.host=localhost
#spring.redis.port=6379
#spring.redis.password=your_redis_password # Optional